"""
contact_map_analysis.py
=======================
Computes Cα–Cα distance-based contact maps for an ensemble of protein
conformers and characterises per-residue conformational flexibility.

For a multi-conformer ensemble (e.g. generated by aSAM, MD, or NMR), this
script:
  1. Loads all PDB files and extracts Cα coordinates.
  2. Identifies the common residue set across all conformers.
  3. Computes a Cα–Cα distance matrix for each conformer.
  4. Derives ensemble statistics: mean distance matrix and element-wise
     standard deviation (a direct measure of pairwise distance variability).
  5. Computes a per-residue flexibility score (mean std across all pairwise
     distances), analogous to a theoretical B-factor.
  6. Ranks and reports the most flexible residues.

Dependencies
------------
    numpy, scipy, matplotlib

    Install via:  pip install numpy scipy matplotlib

Usage
-----
    python contact_map_analysis.py

    Edit the "USER SETTINGS" block below.

Output files
------------
    contact_map_mean.png          – ensemble-mean Cα distance matrix heatmap
    contact_map_std.png           – distance standard-deviation heatmap
    flexibility_profile.png       – per-residue flexibility bar chart
    contact_map_individual.png    – grid of all individual conformer maps
    contact_map_results.npz       – all numerical arrays for downstream use
    most_flexible_residues.csv    – ranked residue list (CSV)
"""

import os
import sys
import csv
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from scipy.spatial.distance import cdist

# ---------------------------------------------------------------------------
# USER SETTINGS
# ---------------------------------------------------------------------------
PDB_DIR      = "/mnt/home/woldring/Ensemble_NMA-PCA/cd1_seq1"
N_CONFORMERS = 10
PDB_PATTERN  = "cluster_repr_{i}.pdb"   # {i} is replaced by 0 … N_CONFORMERS-1
PROTEIN_NAME = "IPNS (isopenicillin N-synthase)"

CONTACT_THRESHOLD_ANG = 8.0   # Å – residues within this distance are "in contact"
TOP_N_RESIDUES        = 20    # most-flexible positions to highlight
CHAIN_ID              = None  # None = first chain found; or e.g. "A"
PLOT_INDIVIDUAL_MAPS  = True  # save a grid of individual conformer distance maps

OUTPUT_DIR      = "/mnt/scratch/woldring/Ensemble_NMA-PCA"

OUTPUT_MEAN_MAP = os.path.join(OUTPUT_DIR, "contact_map_mean.png")
OUTPUT_STD_MAP  = os.path.join(OUTPUT_DIR, "contact_map_std.png")
OUTPUT_FLEX_BAR = os.path.join(OUTPUT_DIR, "flexibility_profile.png")
OUTPUT_NPZ      = os.path.join(OUTPUT_DIR, "contact_map_results.npz")
OUTPUT_CSV      = os.path.join(OUTPUT_DIR, "most_flexible_residues.csv")
# ---------------------------------------------------------------------------


# ── 1. PDB parsing ──────────────────────────────────────────────────────────

def extract_ca_coords(pdb_path: str, chain_id: str | None = None) -> tuple[np.ndarray, list[str]]:
    """
    Parse a PDB file and return Cα coordinates and residue labels.

    Returns
    -------
    coords : np.ndarray, shape (N, 3)
    labels : list of str  –  "<chain>:<resname><resseq>" e.g. "A:ALA14"
    """
    coords: list[list[float]] = []
    labels: list[str] = []
    selected_chain: str | None = chain_id
    seen_residues: set[tuple[str, int, str]] = set()

    with open(pdb_path) as fh:
        for line in fh:
            if not line.startswith("ATOM"):
                continue
            atom_name = line[12:16].strip()
            if atom_name != "CA":
                continue

            chain = line[21]
            if selected_chain is None:
                selected_chain = chain
            if chain != selected_chain:
                continue

            resname = line[17:20].strip()
            resseq  = int(line[22:26].strip())
            icode   = line[26].strip()
            res_key = (chain, resseq, icode)
            if res_key in seen_residues:
                continue
            seen_residues.add(res_key)

            x = float(line[30:38])
            y = float(line[38:46])
            z = float(line[46:54])
            coords.append([x, y, z])
            label_str = f"{chain}:{resname}{resseq}"
            if icode:
                label_str += icode
            labels.append(label_str)

    if not coords:
        sys.exit(
            f"[ERROR] No Cα atoms found in '{pdb_path}' "
            f"(chain filter = '{selected_chain}'). Check CHAIN_ID setting."
        )
    return np.array(coords, dtype=np.float64), labels


# ── 2. Distance matrix ──────────────────────────────────────────────────────

def compute_distance_matrix(coords: np.ndarray) -> np.ndarray:
    """Symmetric pairwise Euclidean distance matrix (Å)."""
    return cdist(coords, coords, metric="euclidean")


# ── 3. Label helpers ────────────────────────────────────────────────────────

def _label_resnum(lbl: str) -> int:
    """Extract integer residue number from a label string."""
    digits = "".join(filter(str.isdigit, lbl.split(":")[1]))
    return int(digits) if digits else 0


# ── 4. Plotting ─────────────────────────────────────────────────────────────

def _residue_tick_params(n: int, labels: list[str], ax, step: int = 20) -> None:
    ticks       = np.arange(0, n, step)
    tick_labels = [labels[i].split(":")[1] for i in ticks]
    ax.set_xticks(ticks)
    ax.set_xticklabels(tick_labels, rotation=45, ha="right", fontsize=7)
    ax.set_yticks(ticks)
    ax.set_yticklabels(tick_labels, fontsize=7)


def plot_distance_map(
    matrix: np.ndarray,
    labels: list[str],
    title: str,
    output_path: str,
    contact_threshold: float | None = CONTACT_THRESHOLD_ANG,
    cmap: str = "viridis_r",
    cbar_label: str = "Cα–Cα distance (Å)",
) -> None:
    """Save a heatmap of a symmetric Cα–Cα distance (or derived) matrix."""
    n    = len(labels)
    fig, ax = plt.subplots(figsize=(8, 7))
    nonzero = matrix[matrix > 0]
    vmax = float(np.percentile(nonzero, 95)) if nonzero.size else 1.0
    im = ax.imshow(matrix, cmap=cmap, origin="upper", vmin=0, vmax=vmax)
    cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label(cbar_label, fontsize=10)
    if contact_threshold is not None:
        ax.contour(matrix, levels=[contact_threshold],
                   colors="white", linewidths=0.8, linestyles="--")
    _residue_tick_params(n, labels, ax)
    ax.set_xlabel("Residue", fontsize=11)
    ax.set_ylabel("Residue", fontsize=11)
    ax.set_title(title, fontsize=12, fontweight="bold")
    plt.tight_layout()
    plt.savefig(output_path, dpi=180)
    plt.close()
    print(f"  Saved → {output_path}")


def plot_flexibility_bar(
    flexibility: np.ndarray,
    labels: list[str],
    output_path: str,
    top_n: int = TOP_N_RESIDUES,
) -> None:
    """Bar chart of the top_n most flexible residues ranked by per-residue mean distance std."""
    ranked_idx    = np.argsort(flexibility)[::-1][:top_n]
    ranked_scores = flexibility[ranked_idx]
    ranked_labels = [labels[i].split(":")[1] for i in ranked_idx]

    fig, ax = plt.subplots(figsize=(10, 5))
    bars = ax.bar(range(top_n), ranked_scores, color="steelblue", edgecolor="white")
    ax.set_xticks(range(top_n))
    ax.set_xticklabels(ranked_labels, rotation=45, ha="right", fontsize=9)
    ax.set_ylabel("Mean Cα–Cα distance std (Å)", fontsize=11)
    ax.set_title(
        f"Top {top_n} most flexible residues — {PROTEIN_NAME}\n"
        f"(ensemble of {N_CONFORMERS} conformers)",
        fontsize=12, fontweight="bold",
    )
    ax.yaxis.set_minor_locator(ticker.AutoMinorLocator())
    ax.grid(axis="y", linestyle="--", alpha=0.4)
    for bar, val in zip(bars, ranked_scores):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.002,
            f"{val:.3f}",
            ha="center", va="bottom", fontsize=7,
        )
    plt.tight_layout()
    plt.savefig(output_path, dpi=180)
    plt.close()
    print(f"  Saved → {output_path}")


def plot_individual_grid(
    dist_matrices: np.ndarray,
    labels: list[str],
    conformer_labels: list[str],
    output_path: str,
    contact_threshold: float = CONTACT_THRESHOLD_ANG,
) -> None:
    """2×5 grid of individual conformer distance maps."""
    n_conf = len(dist_matrices)
    ncols  = 5
    nrows  = (n_conf + ncols - 1) // ncols
    vmax   = float(np.percentile(dist_matrices, 95))

    fig, axes = plt.subplots(nrows, ncols, figsize=(4 * ncols, 4 * nrows))
    axes = np.array(axes).flatten()

    for k, (D, clabel) in enumerate(zip(dist_matrices, conformer_labels)):
        ax = axes[k]
        ax.imshow(D, cmap="viridis_r", origin="upper", vmin=0, vmax=vmax)
        ax.contour(D, levels=[contact_threshold],
                   colors="white", linewidths=0.5, linestyles="--")
        ax.set_title(clabel, fontsize=8, fontweight="bold")
        ax.set_xticks([])
        ax.set_yticks([])

    for k in range(n_conf, len(axes)):
        axes[k].set_visible(False)

    fig.suptitle(
        f"{PROTEIN_NAME} — Individual Conformer Cα Distance Maps",
        fontsize=12, fontweight="bold",
    )
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()
    print(f"  Saved → {output_path}")


# ── 5. Main ─────────────────────────────────────────────────────────────────

def main() -> None:
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    print("=" * 65)
    print(f"  {PROTEIN_NAME}")
    print(f"  Ensemble Cα Contact Map Analysis  ({N_CONFORMERS} conformers)")
    print("=" * 65)

    # --- Build file list ---
    pdb_files = [
        os.path.join(PDB_DIR, PDB_PATTERN.replace("{i}", str(i)))
        for i in range(N_CONFORMERS)
    ]
    conformer_labels = [f"conformer_{i}" for i in range(N_CONFORMERS)]

    # --- Parse PDB files ---
    print(f"\n[1/5] Parsing {N_CONFORMERS} PDB files ...")
    all_coords: list[np.ndarray] = []
    all_labels: list[list[str]] = []
    for i, pdb_path in enumerate(pdb_files):
        if not os.path.isfile(pdb_path):
            sys.exit(f"[ERROR] File not found: {pdb_path}\n"
                     "        Check PDB_DIR and PDB_PATTERN in USER SETTINGS.")
        coords, labels = extract_ca_coords(pdb_path, chain_id=CHAIN_ID)
        all_coords.append(coords)
        all_labels.append(labels)
        print(f"      [{i}] {os.path.basename(pdb_path)}: {len(labels)} Cα atoms")

    # --- Common residue set ---
    print(f"\n[2/5] Identifying common residues across {N_CONFORMERS} conformers ...")
    common_set = set(all_labels[0])
    for lbl_list in all_labels[1:]:
        common_set &= set(lbl_list)
    common_labels = sorted(common_set, key=_label_resnum)
    n = len(common_labels)
    avg_per_conformer = sum(len(l) for l in all_labels) // N_CONFORMERS
    print(f"      Common residue set: {n} residues "
          f"({avg_per_conformer - n} absent in ≥1 conformer)")

    # --- Distance matrices ---
    print(f"\n[3/5] Computing {n}×{n} distance matrices ...")
    dist_matrices = np.zeros((N_CONFORMERS, n, n), dtype=np.float64)
    for k, (coords, lbl_list) in enumerate(zip(all_coords, all_labels)):
        idx_map = {lbl: j for j, lbl in enumerate(lbl_list)}
        indices = np.array([idx_map[lbl] for lbl in common_labels])
        dist_matrices[k] = compute_distance_matrix(coords[indices])
    print("      Done.")

    # --- Ensemble statistics ---
    print(f"\n[4/5] Computing ensemble statistics ...")
    mean_dist = dist_matrices.mean(axis=0)
    # ddof=1 gives the sample standard deviation
    std_dist  = dist_matrices.std(axis=0, ddof=1) if N_CONFORMERS > 1 else dist_matrices.std(axis=0)

    # Per-residue flexibility = mean pairwise distance std across all j
    # (diagonal is always 0, contributing negligibly for large n)
    per_residue_flexibility = std_dist.mean(axis=1)

    # Rank residues
    ranked_idx    = np.argsort(per_residue_flexibility)[::-1]
    ranked_labels = [common_labels[i] for i in ranked_idx]
    ranked_scores = per_residue_flexibility[ranked_idx]
    top_resids    = np.array([_label_resnum(lbl) for lbl in ranked_labels[:TOP_N_RESIDUES]])

    print(f"      Most flexible residue: {ranked_labels[0]}  "
          f"(mean dist std = {ranked_scores[0]:.3f} Å)")
    print(f"      Least flexible residue: {ranked_labels[-1]}  "
          f"(mean dist std = {ranked_scores[-1]:.3f} Å)")

    # --- Save ---
    np.savez_compressed(
        OUTPUT_NPZ,
        dist_matrices=dist_matrices,
        mean_dist=mean_dist,
        std_dist=std_dist,
        per_residue_flexibility=per_residue_flexibility,
        labels=np.array(common_labels),
        conformer_labels=np.array(conformer_labels),
        top_flexible_resids=top_resids,
    )
    print(f"  Saved → {OUTPUT_NPZ}")

    with open(OUTPUT_CSV, "w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["rank", "residue_label", "residue_num", "mean_dist_std_ang"])
        for rank, (lbl, score) in enumerate(zip(ranked_labels, ranked_scores), start=1):
            writer.writerow([rank, lbl, _label_resnum(lbl), f"{score:.4f}"])
    print(f"  Saved → {OUTPUT_CSV}")

    # --- Plots ---
    print("\n[5/5] Generating plots ...")

    plot_distance_map(
        mean_dist, common_labels,
        f"Ensemble-Mean Cα Distance Map — {PROTEIN_NAME}\n"
        f"({N_CONFORMERS} conformers)",
        OUTPUT_MEAN_MAP,
    )

    plot_distance_map(
        std_dist, common_labels,
        f"Cα Distance Std Dev — {PROTEIN_NAME}\n"
        f"(conformational variability across {N_CONFORMERS} conformers)",
        OUTPUT_STD_MAP,
        contact_threshold=None,
        cmap="YlOrRd",
        cbar_label="Cα–Cα distance std dev (Å)",
    )

    plot_flexibility_bar(per_residue_flexibility, common_labels, OUTPUT_FLEX_BAR)

    if PLOT_INDIVIDUAL_MAPS:
        plot_individual_grid(dist_matrices, common_labels, conformer_labels,
                             os.path.join(OUTPUT_DIR, "contact_map_individual.png"))

    # --- Summary ---
    print(f"\n{'─'*65}")
    print(f"  Top {min(TOP_N_RESIDUES, 10)} most flexible residues:\n")
    print(f"  {'Rank':>4}  {'Residue':<18}  {'Mean dist std (Å)':>18}")
    print(f"  {'─'*4}  {'─'*18}  {'─'*18}")
    for rank in range(min(TOP_N_RESIDUES, 10)):
        print(f"  {rank+1:>4}  {ranked_labels[rank]:<18}  {ranked_scores[rank]:>18.3f}")
    print(f"\n  Full ranking saved to '{OUTPUT_CSV}'")
    print("=" * 65)


if __name__ == "__main__":
    main()
