"""
ensemble_pca.py
===============
Principal Component Analysis (PCA) of a multi-conformer protein ensemble.

For an ensemble of N protein conformers (e.g. generated by aSAM, MD, or NMR),
this script:
  1. Loads all PDB files and extracts Cα coordinates.
  2. Identifies the common residue set across all conformers.
  3. Superposes all conformers onto the ensemble mean structure using the
     Kabsch algorithm (removes rigid-body translation and rotation).
  4. Runs PCA via Singular Value Decomposition (SVD) on the 3N-dimensional
     Cα displacement vectors.
  5. Reports per-conformer RMSD to the mean structure.
  6. Produces publication-ready figures:
       – Scree plot (variance explained per PC)
       – PC1 vs PC2 scatter (each point = one conformer, coloured by index)
       – Per-residue displacement profiles for PC1 and PC2
       – Cumulative variance explained
       – Optional comparison of PCA profiles vs GNM/ANM fluctuations

Physical interpretation
-----------------------
Each principal component (PC) is a 3N-dimensional vector describing a
collective deformation of the protein. The first PC captures the largest
single axis of structural variance across the ensemble. The per-residue
displacement magnitude (||PC_k[i]||) shows which residues are most involved
in each principal motion.

For aSAM or MD ensembles, PC1/PC2 typically correspond to the dominant
conformational changes sampled (e.g. domain opening/closing).

Dependencies
------------
    numpy, matplotlib

    Install via:  pip install numpy matplotlib

Usage
-----
    python ensemble_pca.py

    Optionally run contact_map_analysis.py and anm_gnm_analysis.py first to
    enable cross-comparison plots.
    Edit the "USER SETTINGS" block below.

Output files
------------
    pca_scree.png          – variance explained per PC (bar) + cumulative (line)
    pca_scatter.png        – conformer projections onto PC1 vs PC2
    pca_pc1_profile.png    – per-residue Cα displacement along PC1
    pca_pc2_profile.png    – per-residue Cα displacement along PC2
    pca_gnm_comparison.png – PC profiles vs GNM/ANM fluctuations (optional)
    pca_results.npz        – all PCA arrays for downstream use
"""

import os
import sys
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from matplotlib import cm

# ---------------------------------------------------------------------------
# USER SETTINGS
# ---------------------------------------------------------------------------
PDB_DIR      = "/mnt/home/woldring/TopoFormer/Contact_Maps/cd1_seq1"
N_CONFORMERS = 10
PDB_PATTERN  = "cluster_repr_{i}.pdb"
PROTEIN_NAME = "IPNS (isopenicillin N-synthase)"

N_PCS_SHOW   = 5      # PCs shown in the scree plot
CHAIN_ID     = None   # None = first chain found; or e.g. "A"

OUTPUT_SCREE   = "pca_scree.png"
OUTPUT_SCATTER = "pca_scatter.png"
OUTPUT_PC1     = "pca_pc1_profile.png"
OUTPUT_PC2     = "pca_pc2_profile.png"
OUTPUT_COMPARE = "pca_gnm_comparison.png"
OUTPUT_NPZ     = "pca_results.npz"
# ---------------------------------------------------------------------------


# ── PDB parsing ──────────────────────────────────────────────────────────────

def extract_ca_coords(pdb_path: str, chain_id: str | None = None) -> tuple[np.ndarray, list[str]]:
    """
    Parse a PDB file and return Cα coordinates and residue labels.

    Returns
    -------
    coords : np.ndarray, shape (N, 3)
    labels : list of str  –  "<chain>:<resname><resseq>"
    """
    coords: list[list[float]] = []
    labels: list[str] = []
    selected_chain: str | None = chain_id
    seen: set[tuple[str, int, str]] = set()

    with open(pdb_path) as fh:
        for line in fh:
            if not line.startswith("ATOM"):
                continue
            if line[12:16].strip() != "CA":
                continue

            chain = line[21]
            if selected_chain is None:
                selected_chain = chain
            if chain != selected_chain:
                continue

            resname = line[17:20].strip()
            resseq  = int(line[22:26].strip())
            icode   = line[26].strip()
            key     = (chain, resseq, icode)
            if key in seen:
                continue
            seen.add(key)

            coords.append([float(line[30:38]),
                           float(line[38:46]),
                           float(line[46:54])])
            lbl = f"{chain}:{resname}{resseq}"
            if icode:
                lbl += icode
            labels.append(lbl)

    if not coords:
        sys.exit(
            f"[ERROR] No Cα atoms found in '{pdb_path}' "
            f"(chain = '{selected_chain}'). Check CHAIN_ID."
        )
    return np.array(coords, dtype=np.float64), labels


def _label_resnum(lbl: str) -> int:
    digits = "".join(filter(str.isdigit, lbl.split(":")[1]))
    return int(digits) if digits else 0


# ── Structural superposition ─────────────────────────────────────────────────

def kabsch_superpose(mobile: np.ndarray, target: np.ndarray) -> np.ndarray:
    """
    Superpose `mobile` (N_atoms × 3) onto `target` using the Kabsch algorithm.

    The algorithm finds the rotation R that minimises RMSD:
        argmin_R  ||R @ (mobile - c_mob) - (target - c_tgt)||_F

    Returns the rotated+translated mobile coordinates.
    """
    c_mob = mobile.mean(axis=0)
    c_tgt = target.mean(axis=0)
    P = mobile - c_mob
    Q = target - c_tgt

    H = P.T @ Q
    U, _, Vt = np.linalg.svd(H)

    # Correct for improper rotation (reflection) if det < 0
    d = np.sign(np.linalg.det(Vt.T @ U.T))
    R = Vt.T @ np.diag([1.0, 1.0, d]) @ U.T

    return P @ R.T + c_tgt


def superpose_ensemble(
    coords_list: list[np.ndarray],
    n_iter: int = 3,
) -> list[np.ndarray]:
    """
    Iteratively superpose all structures onto the ensemble mean.

    Starting from conformer 0 as the initial reference, the algorithm
    repeatedly recomputes the mean structure and re-superposes all
    conformers to it. Three iterations are sufficient for convergence
    of small ensembles.

    Returns list of superposed (N_atoms × 3) arrays.
    """
    aligned = [kabsch_superpose(c, coords_list[0]) for c in coords_list]
    for _ in range(n_iter):
        mean_struct = np.mean(aligned, axis=0)
        aligned = [kabsch_superpose(c, mean_struct) for c in aligned]
    return aligned


def rmsd(a: np.ndarray, b: np.ndarray) -> float:
    """Root-mean-square deviation between two (N × 3) coordinate arrays."""
    return float(np.sqrt(((a - b) ** 2).sum(axis=1).mean()))


# ── PCA ──────────────────────────────────────────────────────────────────────

def run_pca(aligned_coords: list[np.ndarray]) -> dict:
    """
    Run PCA on an ensemble of superposed Cα coordinate arrays.

    Parameters
    ----------
    aligned_coords : list of (N_atoms × 3) arrays, all superposed to mean.

    Returns
    -------
    dict with keys:
      mean_struct   – (N_atoms, 3) mean structure
      X             – (N_conformers, 3*N_atoms) zero-mean data matrix
      pcs           – (N_pcs, 3*N_atoms) principal component vectors (rows)
      scores        – (N_conformers, N_pcs) conformer projections onto PCs
      var_explained – (N_pcs,) fractional variance explained
      eigenvalues   – (N_pcs,) PCA eigenvalues (Å²)
    """
    n_conf  = len(aligned_coords)
    n_atoms = aligned_coords[0].shape[0]

    # Stack into data matrix (N_conf × 3*N_atoms)
    X_raw = np.array([c.flatten() for c in aligned_coords])  # (N_conf, 3N)

    mean_struct_flat = X_raw.mean(axis=0)
    X = X_raw - mean_struct_flat                              # zero-mean

    # SVD: X = U @ diag(S) @ Vt
    # With full_matrices=False and N_conf < 3N, shapes are:
    #   U  : (N_conf, N_conf)
    #   S  : (N_conf,)
    #   Vt : (N_conf, 3N)  – rows are principal components
    U, S, Vt = np.linalg.svd(X, full_matrices=False)

    eigenvalues  = S ** 2 / (n_conf - 1)          # covariance eigenvalues (Å²)
    var_explained = eigenvalues / eigenvalues.sum()
    scores        = U * S[np.newaxis, :]           # (N_conf, N_pcs)

    return {
        "mean_struct"   : mean_struct_flat.reshape(n_atoms, 3),
        "X"             : X,
        "pcs"           : Vt,                      # (N_pcs, 3N)
        "scores"        : scores,
        "var_explained" : var_explained,
        "eigenvalues"   : eigenvalues,
    }


def pc_residue_profile(pc_vector: np.ndarray, n_atoms: int) -> np.ndarray:
    """
    Per-residue Cα displacement magnitude for a given PC vector.

    Parameters
    ----------
    pc_vector : (3*N_atoms,)  – principal component vector
    n_atoms   : int

    Returns
    -------
    profile : (N_atoms,)  – per-residue ||displacement|| in Å
    """
    return np.linalg.norm(pc_vector.reshape(n_atoms, 3), axis=1)


# ── Plotting ─────────────────────────────────────────────────────────────────

CONF_COLORS = [plt.cm.tab10(i / 10) for i in range(10)]


def plot_scree(var_explained: np.ndarray, n_show: int, out_path: str) -> None:
    """Bar chart of variance explained + cumulative line."""
    n = min(n_show, len(var_explained))
    pct = var_explained[:n] * 100
    cum = np.cumsum(var_explained[:n]) * 100

    fig, ax1 = plt.subplots(figsize=(7, 4))
    ax2 = ax1.twinx()

    ax1.bar(range(1, n + 1), pct, color="steelblue", edgecolor="white",
            alpha=0.85, label="Individual")
    ax2.plot(range(1, n + 1), cum, "o-", color="#E84855", lw=2,
             ms=6, label="Cumulative")
    ax2.axhline(90, color="#E84855", ls="--", lw=0.8, alpha=0.5)

    ax1.set_xlabel("Principal component", fontsize=11)
    ax1.set_ylabel("Variance explained (%)", fontsize=11, color="steelblue")
    ax2.set_ylabel("Cumulative variance (%)", fontsize=11, color="#E84855")
    ax1.set_xticks(range(1, n + 1))
    ax1.set_ylim(0, max(pct) * 1.2)
    ax2.set_ylim(0, 110)
    ax1.tick_params(axis="y", colors="steelblue")
    ax2.tick_params(axis="y", colors="#E84855")

    lines1, lbl1 = ax1.get_legend_handles_labels()
    lines2, lbl2 = ax2.get_legend_handles_labels()
    ax1.legend(lines1 + lines2, lbl1 + lbl2, fontsize=9, loc="center right")

    ax1.set_title(
        f"PCA Scree Plot — {PROTEIN_NAME}\n"
        f"({N_CONFORMERS} conformers, top {n} PCs shown)",
        fontsize=12, fontweight="bold",
    )
    ax1.grid(axis="y", linestyle="--", alpha=0.3)
    ax1.spines[["top", "right"]].set_visible(False)
    plt.tight_layout()
    plt.savefig(out_path, dpi=180)
    plt.close()
    print(f"  Saved → {out_path}")


def plot_scatter(
    scores: np.ndarray,
    var_explained: np.ndarray,
    rmsd_to_mean: list[float],
    out_path: str,
) -> None:
    """Scatter plot of conformer projections onto PC1 vs PC2."""
    fig, ax = plt.subplots(figsize=(7, 6))

    for k in range(len(scores)):
        color = CONF_COLORS[k % len(CONF_COLORS)]
        ax.scatter(scores[k, 0], scores[k, 1], color=color, s=120,
                   zorder=3, edgecolors="white", linewidths=0.8)
        ax.annotate(
            f"c{k}\n({rmsd_to_mean[k]:.2f} Å)",
            (scores[k, 0], scores[k, 1]),
            textcoords="offset points", xytext=(6, 4),
            fontsize=7, color=color,
        )

    ax.axhline(0, color="gray", lw=0.6, ls="--", alpha=0.5)
    ax.axvline(0, color="gray", lw=0.6, ls="--", alpha=0.5)
    ax.set_xlabel(f"PC1  ({var_explained[0]*100:.1f}% variance)", fontsize=11)
    ax.set_ylabel(f"PC2  ({var_explained[1]*100:.1f}% variance)", fontsize=11)
    ax.set_title(
        f"PCA Conformer Projections — {PROTEIN_NAME}\n"
        f"(label = conformer index, parentheses = RMSD to mean, Å)",
        fontsize=11, fontweight="bold",
    )
    ax.grid(linestyle="--", alpha=0.3)
    ax.spines[["top", "right"]].set_visible(False)
    plt.tight_layout()
    plt.savefig(out_path, dpi=180)
    plt.close()
    print(f"  Saved → {out_path}")


def plot_pc_profile(
    profile: np.ndarray,
    resids: np.ndarray,
    pc_num: int,
    var_explained: float,
    top_resids: np.ndarray | None,
    out_path: str,
) -> None:
    """Per-residue Cα displacement magnitude for one PC."""
    fig, ax = plt.subplots(figsize=(12, 4))
    x = np.arange(len(resids))

    if top_resids is not None:
        top_set = set(top_resids)
        for i, r in enumerate(resids):
            if r in top_set:
                ax.axvspan(i - 0.5, i + 0.5, color="#FF006E",
                           alpha=0.15, linewidth=0, zorder=0)

    ax.bar(x, profile, color="steelblue" if pc_num == 1 else "#E84855",
           width=1.0, alpha=0.8)
    ax.set_xticks(range(0, len(resids), 20))
    ax.set_xticklabels(resids[::20], rotation=45, ha="right", fontsize=7)
    ax.set_xlabel("Residue number", fontsize=11)
    ax.set_ylabel("Cα displacement (Å)", fontsize=11)
    ax.set_title(
        f"PC{pc_num} Per-Residue Displacement — {PROTEIN_NAME}\n"
        f"({var_explained*100:.1f}% of ensemble variance  |  "
        f"pink shading = top-flexible residues from contact map)",
        fontsize=11, fontweight="bold",
    )
    ax.yaxis.set_minor_locator(ticker.AutoMinorLocator())
    ax.grid(axis="y", linestyle="--", alpha=0.4)
    ax.spines[["top", "right"]].set_visible(False)

    # Highlight top-5 residues in this PC
    top5_idx = np.argsort(profile)[::-1][:5]
    for idx in top5_idx:
        ax.annotate(
            str(resids[idx]),
            (idx, profile[idx]),
            textcoords="offset points", xytext=(0, 4),
            ha="center", fontsize=7, color="#333333",
        )

    plt.tight_layout()
    plt.savefig(out_path, dpi=180)
    plt.close()
    print(f"  Saved → {out_path}")


def plot_gnm_comparison(
    pc_profiles: list[np.ndarray],
    gnm_flucts_mean: np.ndarray,
    anm_flucts_mean: np.ndarray,
    resids: np.ndarray,
    var_explained: np.ndarray,
    out_path: str,
) -> None:
    """
    Side-by-side comparison of PCA displacement profiles against ensemble-mean
    GNM and ANM fluctuation profiles for the first N_SLOW_MODES slow modes.

    Pearson r values quantify the overlap between each PC and each NMA mode.
    """
    n_pcs   = len(pc_profiles)
    n_modes = gnm_flucts_mean.shape[0]
    n_rows  = max(n_pcs, n_modes)

    fig, axes = plt.subplots(n_rows, 3, figsize=(15, 3.0 * n_rows), sharex=True)
    if n_rows == 1:
        axes = axes.reshape(1, 3)

    x = np.arange(len(resids))

    for k in range(n_rows):
        ax_pc  = axes[k, 0]
        ax_gnm = axes[k, 1]
        ax_anm = axes[k, 2]

        def _norm01(v):
            lo, hi = v.min(), v.max()
            return (v - lo) / (hi - lo + 1e-12)

        if k < n_pcs:
            pc_norm = _norm01(pc_profiles[k])
            ax_pc.bar(x, pc_profiles[k], color="steelblue", width=1.0, alpha=0.8)
            ax_pc.set_title(f"PC{k+1}  ({var_explained[k]*100:.1f}%)",
                            fontsize=10, fontweight="bold")
            ax_pc.set_ylabel("Disp. (Å)", fontsize=9)
        else:
            ax_pc.set_visible(False)
            pc_norm = None

        for ax_nma, flucts_mean, model_name, color in [
            (ax_gnm, gnm_flucts_mean, "GNM", "#2E86AB"),
            (ax_anm, anm_flucts_mean, "ANM", "#E84855"),
        ]:
            if k < n_modes:
                f_norm = _norm01(flucts_mean[k])
                ax_nma.plot(x, f_norm, color=color, lw=1.8,
                            label=f"{model_name} mode {k+1}")
                ax_nma.fill_between(x, f_norm, alpha=0.15, color=color)
                if pc_norm is not None:
                    r = float(np.corrcoef(f_norm, pc_norm)[0, 1])
                    ax_nma.plot(x, pc_norm, color="#333333", lw=1.0, ls="--",
                                alpha=0.7, label=f"PC{k+1} (norm.)")
                    ax_nma.set_title(
                        f"{model_name} mode {k+1}  [r = {r:+.3f}]",
                        fontsize=10, fontweight="bold",
                    )
                else:
                    ax_nma.set_title(f"{model_name} mode {k+1}",
                                     fontsize=10, fontweight="bold")
                ax_nma.set_ylabel("Norm. value", fontsize=9)
                ax_nma.set_yticks([0, 0.5, 1])
                ax_nma.set_ylim(-0.05, 1.15)
                ax_nma.legend(fontsize=7, loc="upper right")
                ax_nma.grid(axis="y", linestyle="--", alpha=0.3)
                ax_nma.spines[["top", "right"]].set_visible(False)
            else:
                ax_nma.set_visible(False)

        for ax in axes[k]:
            if ax.get_visible():
                ax.set_xticks(range(0, len(resids), 20))
                ax.set_xticklabels(resids[::20], rotation=45,
                                   ha="right", fontsize=6)

    for col in range(3):
        if axes[-1, col].get_visible():
            axes[-1, col].set_xlabel("Residue number", fontsize=9)

    fig.suptitle(
        f"PCA vs GNM/ANM Mode Comparison — {PROTEIN_NAME}\n"
        f"(Pearson r = overlap between PC and NMA mode; higher |r| = better agreement)",
        fontsize=12, fontweight="bold", y=1.005,
    )
    plt.tight_layout()
    plt.savefig(out_path, dpi=180, bbox_inches="tight")
    plt.close()
    print(f"  Saved → {out_path}")


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    print("=" * 65)
    print(f"  {PROTEIN_NAME}")
    print(f"  Ensemble PCA  ({N_CONFORMERS} conformers)")
    print("=" * 65)

    pdb_files = [
        os.path.join(PDB_DIR, PDB_PATTERN.replace("{i}", str(i)))
        for i in range(N_CONFORMERS)
    ]
    for p in pdb_files:
        if not os.path.isfile(p):
            sys.exit(f"[ERROR] File not found: {p}\n"
                     "        Check PDB_DIR and PDB_PATTERN in USER SETTINGS.")

    # ── Load Cα coordinates ───────────────────────────────────────────────────
    print(f"\n[1/5] Parsing {N_CONFORMERS} PDB files ...")
    all_coords: list[np.ndarray] = []
    all_labels: list[list[str]] = []
    for i, pdb_path in enumerate(pdb_files):
        coords, labels = extract_ca_coords(pdb_path, chain_id=CHAIN_ID)
        all_coords.append(coords)
        all_labels.append(labels)
        print(f"      [{i}] {os.path.basename(pdb_path)}: {len(labels)} Cα atoms")

    # ── Common residue set ────────────────────────────────────────────────────
    print(f"\n[2/5] Identifying common residue set ...")
    common_set = set(all_labels[0])
    for lbl_list in all_labels[1:]:
        common_set &= set(lbl_list)
    common_labels = sorted(common_set, key=_label_resnum)
    n_res = len(common_labels)
    resids = np.array([_label_resnum(lbl) for lbl in common_labels])
    print(f"      {n_res} common residues")

    # Select and order each conformer to the common set
    coords_selected: list[np.ndarray] = []
    for coords, lbl_list in zip(all_coords, all_labels):
        idx_map = {lbl: j for j, lbl in enumerate(lbl_list)}
        indices = np.array([idx_map[lbl] for lbl in common_labels])
        coords_selected.append(coords[indices])

    # ── Kabsch superposition ──────────────────────────────────────────────────
    print(f"\n[3/5] Superposing all conformers onto ensemble mean (Kabsch algorithm) ...")
    aligned_coords = superpose_ensemble(coords_selected, n_iter=3)
    mean_struct    = np.mean(aligned_coords, axis=0)

    rmsd_to_mean = [rmsd(c, mean_struct) for c in aligned_coords]
    for k, r in enumerate(rmsd_to_mean):
        print(f"      Conformer {k}: RMSD to mean = {r:.3f} Å")
    print(f"      Mean RMSD = {np.mean(rmsd_to_mean):.3f} Å  "
          f"(range {np.min(rmsd_to_mean):.3f}–{np.max(rmsd_to_mean):.3f} Å)")

    # ── PCA ───────────────────────────────────────────────────────────────────
    print(f"\n[4/5] Running PCA via SVD ...")
    pca = run_pca(aligned_coords)

    n_pcs          = pca["scores"].shape[1]
    var_explained  = pca["var_explained"]
    scores         = pca["scores"]
    pcs            = pca["pcs"]

    print(f"      {n_pcs} PCs computed (= number of conformers minus 1)")
    for k in range(min(N_PCS_SHOW, n_pcs)):
        print(f"      PC{k+1}: {var_explained[k]*100:.1f}% variance")

    # Per-residue displacement profiles
    pc_profiles = [pc_residue_profile(pcs[k], n_res) for k in range(n_pcs)]

    # ── Load top flexible residues for annotation ─────────────────────────────
    top_resids = None
    try:
        npz        = np.load("contact_map_results.npz", allow_pickle=True)
        top_resids = npz["top_flexible_resids"]
        print(f"      Loaded top_flexible_resids from contact_map_results.npz")
    except FileNotFoundError:
        print("      contact_map_results.npz not found — skipping flexibility annotations.")

    # ── Load GNM/ANM results for comparison ──────────────────────────────────
    gnm_flucts_mean = anm_flucts_mean = None
    try:
        nma = np.load("anm_gnm_results.npz", allow_pickle=True)
        gnm_flucts_mean = nma["gnm_flucts_mean"]
        anm_flucts_mean = nma["anm_flucts_mean"]
        print("      Loaded GNM/ANM results from anm_gnm_results.npz")
    except FileNotFoundError:
        print("      anm_gnm_results.npz not found — skipping GNM/ANM comparison.")

    # ── Save results ──────────────────────────────────────────────────────────
    np.savez_compressed(
        OUTPUT_NPZ,
        pcs=pcs,
        scores=scores,
        var_explained=var_explained,
        eigenvalues=pca["eigenvalues"],
        mean_struct=mean_struct,
        aligned_coords=np.array(aligned_coords),
        pc1_profile=pc_profiles[0],
        pc2_profile=pc_profiles[1] if n_pcs > 1 else np.zeros(n_res),
        resids=resids,
        rmsd_to_mean=np.array(rmsd_to_mean),
    )
    print(f"  Saved → {OUTPUT_NPZ}")

    # ── Plots ─────────────────────────────────────────────────────────────────
    print("\n[5/5] Generating plots ...")

    plot_scree(var_explained, N_PCS_SHOW, OUTPUT_SCREE)

    plot_scatter(scores, var_explained, rmsd_to_mean, OUTPUT_SCATTER)

    plot_pc_profile(
        pc_profiles[0], resids, 1, var_explained[0], top_resids, OUTPUT_PC1,
    )
    if n_pcs > 1:
        plot_pc_profile(
            pc_profiles[1], resids, 2, var_explained[1], top_resids, OUTPUT_PC2,
        )

    if gnm_flucts_mean is not None and anm_flucts_mean is not None:
        n_compare = min(n_pcs, gnm_flucts_mean.shape[0])
        plot_gnm_comparison(
            pc_profiles[:n_compare],
            gnm_flucts_mean[:n_compare],
            anm_flucts_mean[:n_compare],
            resids, var_explained, OUTPUT_COMPARE,
        )

    # ── Summary ───────────────────────────────────────────────────────────────
    print(f"\n{'─'*65}")
    print(f"  PCA SUMMARY\n")
    print(f"  {'PC':>4}  {'Variance (%)':>14}  {'Cumulative (%)':>16}")
    print(f"  {'─'*4}  {'─'*14}  {'─'*16}")
    cumulative = 0.0
    for k in range(min(N_PCS_SHOW, n_pcs)):
        cumulative += var_explained[k] * 100
        print(f"  {k+1:>4}  {var_explained[k]*100:>14.1f}  {cumulative:>16.1f}")

    print(f"\n  Top-5 residues by PC1 displacement:")
    top5_pc1 = np.argsort(pc_profiles[0])[::-1][:5]
    for rank, idx in enumerate(top5_pc1, 1):
        print(f"    {rank}. residue {resids[idx]:4d}  ({pc_profiles[0][idx]:.3f} Å)")
    if n_pcs > 1:
        print(f"\n  Top-5 residues by PC2 displacement:")
        top5_pc2 = np.argsort(pc_profiles[1])[::-1][:5]
        for rank, idx in enumerate(top5_pc2, 1):
            print(f"    {rank}. residue {resids[idx]:4d}  ({pc_profiles[1][idx]:.3f} Å)")

    print(f"\n  RMSD to ensemble mean:  "
          f"min={np.min(rmsd_to_mean):.3f}  "
          f"max={np.max(rmsd_to_mean):.3f}  "
          f"avg={np.mean(rmsd_to_mean):.3f}  Å")
    print("=" * 65)


if __name__ == "__main__":
    main()
